import { auth, db } from './firebase-config.js';
import { addDoc, collection, getDocs } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';

const ROLE=window.IMS_ROLE||'admin',CAN_EDIT=['manager','superadmin'].includes(ROLE),byId=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cls='w-full bg-slate-950 border border-slate-700 rounded-lg px-3 py-2.5 text-sm';
const norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),now=()=>new Date().toISOString();
let busy=false;
async function settings(){const s=await getDocs(collection(db,'settings'));return s.docs.map(d=>({id:d.id,...d.data()}));}
function unique(all,type){const seen=new Set();return all.filter(x=>x.type===type&&x.status!=='inactive').filter(x=>{const k=norm(x.value);if(!k||seen.has(k))return false;seen.add(k);return true;}).sort((a,b)=>String(a.value).localeCompare(String(b.value),undefined,{numeric:true,sensitivity:'base'}));}
function row(type,label,all){return `<section class="border border-slate-800 rounded-xl p-3"><div class="font-semibold text-sm mb-2">${label}</div><form class="cmRow flex flex-col sm:flex-row gap-2" data-type="${type}"><input class="cmValue ${cls}" placeholder="Add ${label}"><button class="bg-emerald-700 px-4 py-2.5 rounded-lg text-xs font-bold sm:w-32">Add</button></form><div class="mt-3 flex flex-wrap gap-2">${unique(all,type).map(x=>`<span class="bg-slate-950 border border-slate-800 rounded-lg px-2 py-1 text-xs">${esc(x.value)}</span>`).join('')||'<span class="text-xs text-slate-600">None</span>'}</div></section>`;}
function tidyCoreMasters(){const root=byId('appContent');if(!root||!/Global Settings/i.test(byId('pageTitle')?.textContent||''))return;const cards=[...root.querySelectorAll(':scope > div > section')];for(const card of cards){const title=card.querySelector('h2')?.textContent?.trim();if(title==='Categories')card.remove();}const grid=root.querySelector(':scope > div.grid');if(grid){grid.classList.remove('lg:grid-cols-3');grid.classList.add('grid-cols-1');}}
async function mount(){if(!CAN_EDIT||byId('imsClassificationMaster')||!/Global Settings/i.test(byId('pageTitle')?.textContent||''))return;const root=byId('appContent');if(!root)return;tidyCoreMasters();const all=await settings();if(byId('imsClassificationMaster')||!/Global Settings/i.test(byId('pageTitle')?.textContent||''))return;const sec=document.createElement('section');sec.id='imsClassificationMaster';sec.className='bg-slate-900 border border-slate-800 rounded-2xl p-4 sm:p-5 shadow-xl mt-5';sec.innerHTML=`<h2 class="font-bold mb-1">Independent Item Masters</h2><p class="text-xs text-slate-500 mb-4">Each master type is independent. One type is shown per row so no relationship is implied between Category, Brand, Model, Grade or Specification.</p><div id="cmRows" class="space-y-3">${row('category','Category',all)}${row('brand','Brand',all)}${row('model','Model',all)}${row('grade','Grade',all)}${row('specification','Specification',all)}</div>`;root.appendChild(sec);sec.querySelectorAll('.cmRow').forEach(f=>f.onsubmit=save);}
async function save(e){e.preventDefault();if(busy)return;const form=e.currentTarget,type=form.dataset.type,input=form.querySelector('.cmValue'),value=input.value.trim().replace(/\s+/g,' ');if(!value)return;busy=true;const btn=form.querySelector('button');btn.disabled=true;btn.textContent='Saving...';try{const all=await settings();if(all.some(x=>x.type===type&&norm(x.value)===norm(value)&&x.status!=='inactive'))return alert('This value already exists.');await addDoc(collection(db,'settings'),{type,value,normalizedValue:norm(value),status:'active',createdAt:now(),createdBy:auth.currentUser?.email||''});input.value='';byId('imsClassificationMaster')?.remove();await mount();}catch(err){console.error(err);alert(err?.message||String(err));}finally{busy=false;if(btn){btn.disabled=false;btn.textContent='Add';}}}
let t;new MutationObserver(()=>{clearTimeout(t);t=setTimeout(()=>{tidyCoreMasters();mount().catch(()=>{})},25)}).observe(document.body,{childList:true,subtree:true});tidyCoreMasters();mount().catch(()=>{});
