import { db } from './firebase-config.js';
import { collection, doc, getDoc, getDocs, limit, orderBy, query, where } from 'https://www.gstatic.com/firebasejs/11.0.1/firebase-firestore.js';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),norm=s=>String(s??'').trim().replace(/\s+/g,' ').toLowerCase(),pageSize=10;let items=[],currentQuery='',allInventory=[],pages={client:0,supplier:0,transit:0,maintenance:0};
function itemQty(i){const b=Array.isArray(i.stockBalances)?i.stockBalances:[];return b.length?b.reduce((n,x)=>n+Number(x.qty||0),0):Number(i.quantity??i.qty??0)}
function itemHaystack(i){return norm(`${i.alias||''} ${i.itemCode||''} ${i.name||''} ${i.category||''} ${i.brand||''} ${i.model||''} ${i.grade||''} ${i.specification||''} ${i.supplierName||''} ${i.currentLocation||''} ${i.status||''} ${JSON.stringify(i.stockBalances||[])}`)}
function mergeUnique(list){const m=new Map();list.forEach(x=>{if(x?.id)m.set(x.id,x)});return[...m.values()]}
async function latestItems(){try{const s=await getDocs(query(collection(db,'inventory'),orderBy('createdAt','desc'),limit(pageSize)));return s.docs.map(d=>({id:d.id,...d.data()}))}catch{const s=await getDocs(query(collection(db,'inventory'),limit(pageSize)));return s.docs.map(d=>({id:d.id,...d.data()}))}}
async function searchItems(raw){const qn=norm(raw);if(!qn)return latestItems();const found=[];for(const field of ['itemCode','alias'])try{const exact=await getDocs(query(collection(db,'inventory'),where(field,'==',raw.trim()),limit(10)));exact.forEach(d=>found.push({id:d.id,...d.data()}))}catch{}try{const refs=await getDocs(query(collection(db,'document_refs'),where('refNumber','==',raw.trim()),limit(20)));for(const r of refs.docs){const id=r.data().itemId;if(id)try{const s=await getDoc(doc(db,'inventory',id));if(s.exists())found.push({id:s.id,...s.data()})}catch{}}}catch{}try{const recent=await getDocs(query(collection(db,'inventory'),orderBy('lastEditedAt','desc'),limit(100)));recent.forEach(d=>{const i={id:d.id,...d.data()};if(itemHaystack(i).includes(qn))found.push(i)})}catch{}return mergeUnique(found).slice(0,100)}
function identity(i){return `<div class="font-semibold text-sm"><span class="text-cyan-300">${esc(i.alias||'No Alias')}</span> · <span class="font-mono text-xs">${esc(i.itemCode||'')}</span> · ${esc(i.name||'')}</div>`}
function render(){const mount=document.getElementById('itemFindResults');if(!mount)return;const label=currentQuery?`${items.length} matching item${items.length===1?'':'s'}`:`Latest ${items.length} items`;mount.innerHTML=`<div class="flex items-center justify-between gap-3 mb-2"><div class="text-xs font-semibold text-slate-400">${esc(label)}</div><div class="text-[10px] text-slate-600">Alias · IMS Item ID · Item Name</div></div>`+(items.map(i=>`<button onclick="openItem('${i.id}')" class="w-full text-left bg-slate-950 hover:bg-slate-800 border border-slate-800 rounded-xl p-3 mb-2">${identity(i)}<div class="text-[11px] text-slate-500">${esc([i.category,i.brand,i.model,i.specification].filter(Boolean).join(' · ')||'No classification')}</div><div class="text-[10px] text-slate-500 mt-1">${esc(i.status||'')} · ${esc(i.currentLocation||'')} · ${esc(itemQty(i))} ${esc(i.unit||'')}</div></button>`).join('')||'<div class="text-sm text-slate-500">No matching items.</div>')}
async function runSearch(){const raw=document.getElementById('itemFind')?.value||'';currentQuery=norm(raw);items=await searchItems(raw);render()}
function hasBalance(i,status){return (Array.isArray(i.stockBalances)?i.stockBalances:[]).some(b=>Number(b.qty||0)>0&&b.status===status)}
function groupItems(key){if(key==='client')return allInventory.filter(i=>hasBalance(i,'At Client')||i.status==='At Client');if(key==='supplier')return allInventory.filter(i=>hasBalance(i,'At Supplier')||i.status==='At Supplier');if(key==='transit')return allInventory.filter(i=>hasBalance(i,'In Transit')||i.status==='In Transit');return allInventory.filter(i=>hasBalance(i,'Maintenance')||i.status==='Maintenance')}
function groupCard(key,title){const list=groupItems(key).sort((a,b)=>String(a.alias||a.itemCode).localeCompare(String(b.alias||b.itemCode),undefined,{numeric:true,sensitivity:'base'})),max=Math.max(1,Math.ceil(list.length/pageSize));pages[key]=Math.min(pages[key],max-1);const slice=list.slice(pages[key]*pageSize,(pages[key]+1)*pageSize);return `<section class="bg-slate-900 border border-slate-800 rounded-2xl p-4"><div class="flex justify-between items-center mb-3"><div><div class="font-bold">${title}</div><div class="text-[10px] text-slate-500">${list.length} active item${list.length===1?'':'s'} · Alias first</div></div><div class="text-xs text-slate-500">${pages[key]+1}/${max}</div></div><div class="space-y-2">${slice.map(i=>`<button onclick="openItem('${i.id}')" class="w-full text-left bg-slate-950 border border-slate-800 rounded-lg p-2">${identity(i)}<div class="text-[10px] text-slate-500">${esc(i.currentLocation||i.status||'')}</div></button>`).join('')||'<div class="text-xs text-slate-600">No active items.</div>'}</div>${list.length>pageSize?`<div class="flex justify-end gap-2 mt-3"><button data-active-page="${key}" data-d="-1" class="bg-slate-800 px-3 py-1.5 rounded text-xs" ${pages[key]===0?'disabled':''}>Previous</button><button data-active-page="${key}" data-d="1" class="bg-slate-800 px-3 py-1.5 rounded text-xs" ${pages[key]>=max-1?'disabled':''}>Next</button></div>`:''}</section>`}
function renderActive(){const mount=document.getElementById('imsActiveItems');if(!mount)return;mount.innerHTML=groupCard('client','At Client')+groupCard('supplier','At Supplier')+groupCard('transit','In Transit')+groupCard('maintenance','Maintenance');mount.querySelectorAll('[data-active-page]').forEach(b=>b.onclick=()=>{pages[b.dataset.activePage]+=Number(b.dataset.d);renderActive()})}
async function enhanceActive(){if(!/Main Workspace/i.test(document.getElementById('pageTitle')?.textContent||'')||document.getElementById('imsActiveItems'))return;const app=document.getElementById('appContent');if(!app)return;try{const s=await getDocs(collection(db,'inventory'));allInventory=s.docs.map(d=>({id:d.id,...d.data()}))}catch{return}const mount=document.createElement('div');mount.id='imsActiveItems';mount.className='grid gap-5 mt-5';app.appendChild(mount);renderActive()}
async function enhanceFinder(){const input=document.getElementById('itemFind'),button=document.getElementById('itemFindBtn'),mount=document.getElementById('itemFindResults');if(!input||!button||!mount||mount.dataset.imsRecentEnhanced==='3')return;mount.dataset.imsRecentEnhanced='3';button.onclick=runSearch;input.onkeyup=e=>{if(e.key==='Enter')runSearch()};currentQuery='';items=await latestItems();render()}
function enhance(){enhanceFinder();enhanceActive()}new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});enhance();